import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/NavBar";
import { Inter } from 'next/font/google';
import { CartProvider } from "./src/context/CartContext";

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: "Bear Burguer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${inter.className} bg-zinc-100`}>
        <CartProvider>
          <Navbar />
          <main className="container mx-auto p-4">
            {children}
          </main>
        </CartProvider>

      </body>
    </html>
  );
}
